services:
  #---------------------- DATABASES -------------------------
  user_postgres:
    image: postgres:latest
    container_name: user_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
    ports:
      - ${USER_SERVICE_POSTGRES_PORTS}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${USER_SERVICE_POSTGRES_USER} -d ${USER_SERVICE_POSTGRES_PASSWORD} -t 10',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  user_hangfire_postgres:
    image: postgres:latest
    container_name: user_hangfire_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${HANGFIRE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HANGFIRE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HANGFIRE_POSTGRES_DB}
    ports:
      - ${HANGFIRE_POSTGRES_PORTS}
    volumes:
      - user_hangfire_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${HANGFIRE_POSTGRES_USER} -d ${HANGFIRE_POSTGRES_DB} -t 10'
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  meeting_postgres:
    image: postgres:latest
    container_name: meeting_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${MEETING_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MEETING_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MEETING_SERVICE_POSTGRES_DB}
    ports:
      - ${MEETING_SERVICE_POSTGRES_PORTS}
    volumes:
      - meeting_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${MEETING_SERVICE_POSTGRES_USER} -d ${MEETING_SERVICE_POSTGRES_PASSWORD} -t 10',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  user_redis:
    image: redis:latest
    container_name: user_redis
    env_file:
      - .env
    ports:
      - ${USER_SERVICE_REDIS_PORTS}
    volumes:
      - user_redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  schedule_redis:
    image: redis:latest
    container_name: schedule_redis
    env_file:
      - .env
    ports:
      - ${SCHEDULE_SERVICE_REDIS_PORTS}
    volumes:
      - schedule_redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  meeting_redis:
    image: redis:latest
    container_name: meeting_redis
    env_file:
      - .env
    ports:
      - ${MEETING_SERVICE_REDIS_PORTS}
    volumes:
      - meeting_redis_data:/var/lib/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
        - ${MONGO_PORTS}
    volumes:
      - mongodb_data:/var/lib/mongodb/data
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    command: mongod --replSet rs0 --bind_ip_all
#    env_file:
#      - .env
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    ports:
#      - ${MONGO_PORTS}
#    volumes:
#      - mongodb_data:/var/lib/mongodb/data
  
  #---------------------- PG-ADMIN --------------------------
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_PORTS}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    restart: always
  
  #---------------------- MONGO_DB EXPRESS ------------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file: .env
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "${MONGO_EXPRESS_PORT}"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
  
  #---------------------- MESSAGE-BROKER --------------------
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: ${RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS}
    ports:
      - "${RABBITMQ_PORT_AMQP}"
      - "${RABBITMQ_PORT_UI}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
  
  #---------------------- SERVICES --------------------------
  api_gateway:
    build:
      context: .
      dockerfile: /backend/ApiGateway/ApiGateway.Api/Dockerfile
    container_name: api_gateway
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${API_GATEWAY_SERVICE_PORTS}
    depends_on:
      - user_service
      - schedule_service
      - meeting_service
  #    healthcheck:
  #      test: [ "CMD", "curl", "-f", "http://localhost:${API_GATEWAY_SERVICE_PORTS%:*}/health" ]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 3

  user_service:
    build:
      context: .
      dockerfile: /backend/UserService/UserService.Api/Dockerfile
    container_name: user_service
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${USER_SERVICE_PORTS}
    depends_on:
      - user_postgres
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://localhost:${USER_SERVICE_PORTS%:*}/health" ]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3

  schedule_service:
    build:
      context: .
      dockerfile: /backend/ScheduleService/ScheduleService.Api/Dockerfile
    container_name: schedule_service
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${SCHEDULE_SERVICE_PORTS}
    depends_on:
      - mongodb
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://localhost:${SCHEDULE_SERVICE_PORTS%:*}/health" ]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3

  meeting_service:
    build:
      context: .
      dockerfile: /backend/MeetingService/MeetingService.Api/Dockerfile
    container_name: meeting_service
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - ${MEETING_SERVICE_PORTS}
    depends_on:
      - meeting_postgres
      - rabbitmq
    #    healthcheck:
    #      test: [ "CMD", "curl", "-f", "http://localhost:${MEETING_SERVICE_PORTS%:*}/health" ]
    #      interval: 30s
    #      timeout: 10s
    #      retries: 3

  #---------------------- ELK -------------------------------
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.14.3
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - ${ELASTIC_PORTS}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health?wait_for_status=green&timeout=50s" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk
  
  logstash:
    image: logstash:7.9.1
    container_name: logstash
    env_file:
      - .env
    ports:
      - ${LOGSTASH_PORTS}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk
  
  kibana:
    image: kibana:8.14.3
    container_name: kibana
    env_file:
      - .env
    ports:
      - ${KIBANA_PORTS}
    depends_on:
      - elasticsearch
    volumes:
      - kibana_data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=${ELASTIC_URL}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5601/api/status" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elk

#---------------------- NETWORKS ----------------------------
networks:
  elk:
    driver: bridge

#---------------------- VOLUMES -----------------------------
volumes:
  user_postgres_data:
  user_hangfire_postgres_data:
  meeting_postgres_data:
  user_redis_data:
  schedule_redis_data:
  meeting_redis_data:
  mongodb_data:
  rabbitmq_data:
  elasticsearch_data:
  kibana_data:
  pgadmin_data: