// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250324140610_AddTokenStringToTokenTable")]
    partial class AddTokenStringToTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5478671-3600-42df-9f03-5f2350c4f034"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("de1eeff9-94fc-4eb4-9903-ded1fdf0c7db"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("90d2e819-ddcd-4fd0-962e-fbc66efe5a57"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("36d3c130-f67d-4701-971e-5135244a8a4e"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc72797e-4041-407b-b784-0567d4248783"),
                            CreatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3208),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3316),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("e68b001e-54a2-49e7-999c-14e7e5c7492e"),
                            CreatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3565),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3565),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("455bc0d7-2ab0-46b6-b543-b078ee78132f"),
                            CreatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3568),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 24, 14, 6, 10, 218, DateTimeKind.Utc).AddTicks(3568),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("dc72797e-4041-407b-b784-0567d4248783"),
                            RoleId = new Guid("de1eeff9-94fc-4eb4-9903-ded1fdf0c7db")
                        },
                        new
                        {
                            UserId = new Guid("dc72797e-4041-407b-b784-0567d4248783"),
                            RoleId = new Guid("90d2e819-ddcd-4fd0-962e-fbc66efe5a57")
                        },
                        new
                        {
                            UserId = new Guid("dc72797e-4041-407b-b784-0567d4248783"),
                            RoleId = new Guid("36d3c130-f67d-4701-971e-5135244a8a4e")
                        },
                        new
                        {
                            UserId = new Guid("e68b001e-54a2-49e7-999c-14e7e5c7492e"),
                            RoleId = new Guid("de1eeff9-94fc-4eb4-9903-ded1fdf0c7db")
                        },
                        new
                        {
                            UserId = new Guid("e68b001e-54a2-49e7-999c-14e7e5c7492e"),
                            RoleId = new Guid("90d2e819-ddcd-4fd0-962e-fbc66efe5a57")
                        },
                        new
                        {
                            UserId = new Guid("455bc0d7-2ab0-46b6-b543-b078ee78132f"),
                            RoleId = new Guid("de1eeff9-94fc-4eb4-9903-ded1fdf0c7db")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
