// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250325091153_IsConfirmedPropertyAdd")]
    partial class IsConfirmedPropertyAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b92bca83-5a80-4323-8c93-635e3486998c"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("c7ed4f3b-e0e3-40e1-8dda-0d5c7b201a0c"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("b865f0c0-e730-49a5-8c80-9b9b4f5b8d56"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("b9042180-949b-470c-9ebb-4fb6b1b27404"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d360b8e-d55d-45dc-86a0-994062809dab"),
                            CreatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6294),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6400),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("8f841611-a026-48a1-aee8-669d5760a45f"),
                            CreatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6701),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6702),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("727dd265-0f1a-48f3-bce0-7fe085e92310"),
                            CreatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6704),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsConfirmed = false,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 25, 9, 11, 52, 147, DateTimeKind.Utc).AddTicks(6704),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("5d360b8e-d55d-45dc-86a0-994062809dab"),
                            RoleId = new Guid("c7ed4f3b-e0e3-40e1-8dda-0d5c7b201a0c")
                        },
                        new
                        {
                            UserId = new Guid("5d360b8e-d55d-45dc-86a0-994062809dab"),
                            RoleId = new Guid("b865f0c0-e730-49a5-8c80-9b9b4f5b8d56")
                        },
                        new
                        {
                            UserId = new Guid("5d360b8e-d55d-45dc-86a0-994062809dab"),
                            RoleId = new Guid("b9042180-949b-470c-9ebb-4fb6b1b27404")
                        },
                        new
                        {
                            UserId = new Guid("8f841611-a026-48a1-aee8-669d5760a45f"),
                            RoleId = new Guid("c7ed4f3b-e0e3-40e1-8dda-0d5c7b201a0c")
                        },
                        new
                        {
                            UserId = new Guid("8f841611-a026-48a1-aee8-669d5760a45f"),
                            RoleId = new Guid("b865f0c0-e730-49a5-8c80-9b9b4f5b8d56")
                        },
                        new
                        {
                            UserId = new Guid("727dd265-0f1a-48f3-bce0-7fe085e92310"),
                            RoleId = new Guid("c7ed4f3b-e0e3-40e1-8dda-0d5c7b201a0c")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
