// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250324065442_UpdatedTokenTable")]
    partial class UpdatedTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df15b981-6275-49c1-b94c-0de7eba98bac"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("f63116d0-a0f4-4cdb-aae4-1d635f655f12"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("9eee284a-57b4-496c-8ca6-660c6d848d6a"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("1c1b9d23-49e4-4ab1-b970-ce17d67b3035"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Token")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20bf313c-eb72-42e7-8346-6e1a7667c6fc"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9087),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9206),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("b2f3c585-7a76-46e1-95e4-5862fb21b50f"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9430),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9430),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("937efb8c-804a-429a-871b-33bfc4efec3e"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9432),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 54, 42, 427, DateTimeKind.Utc).AddTicks(9433),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("20bf313c-eb72-42e7-8346-6e1a7667c6fc"),
                            RoleId = new Guid("f63116d0-a0f4-4cdb-aae4-1d635f655f12")
                        },
                        new
                        {
                            UserId = new Guid("20bf313c-eb72-42e7-8346-6e1a7667c6fc"),
                            RoleId = new Guid("9eee284a-57b4-496c-8ca6-660c6d848d6a")
                        },
                        new
                        {
                            UserId = new Guid("20bf313c-eb72-42e7-8346-6e1a7667c6fc"),
                            RoleId = new Guid("1c1b9d23-49e4-4ab1-b970-ce17d67b3035")
                        },
                        new
                        {
                            UserId = new Guid("b2f3c585-7a76-46e1-95e4-5862fb21b50f"),
                            RoleId = new Guid("f63116d0-a0f4-4cdb-aae4-1d635f655f12")
                        },
                        new
                        {
                            UserId = new Guid("b2f3c585-7a76-46e1-95e4-5862fb21b50f"),
                            RoleId = new Guid("9eee284a-57b4-496c-8ca6-660c6d848d6a")
                        },
                        new
                        {
                            UserId = new Guid("937efb8c-804a-429a-871b-33bfc4efec3e"),
                            RoleId = new Guid("f63116d0-a0f4-4cdb-aae4-1d635f655f12")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
