// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250331115443_LasLoginColumn")]
    partial class LasLoginColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af7175c3-92c2-484b-81a6-547cfeb18ec8"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("2ef4db94-34d6-4264-aebc-eeb0d2908a97"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("d089bf57-5915-418c-bbbf-f19e453aee79"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("da138ce8-397b-4c68-98eb-87c211c12883"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ba32b68-fb3a-499e-a784-8cd1bba940da"),
                            CreatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7331),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastLoginAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7439),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("d724d7e7-b0df-47a7-989c-c373eff365a8"),
                            CreatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7726),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastLoginAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7726),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("76faed9e-cca9-4e5b-98bf-837fa3bdd501"),
                            CreatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7728),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsConfirmed = false,
                            IsDeleted = false,
                            LastLoginAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 31, 11, 54, 43, 385, DateTimeKind.Utc).AddTicks(7729),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1ba32b68-fb3a-499e-a784-8cd1bba940da"),
                            RoleId = new Guid("2ef4db94-34d6-4264-aebc-eeb0d2908a97")
                        },
                        new
                        {
                            UserId = new Guid("1ba32b68-fb3a-499e-a784-8cd1bba940da"),
                            RoleId = new Guid("d089bf57-5915-418c-bbbf-f19e453aee79")
                        },
                        new
                        {
                            UserId = new Guid("1ba32b68-fb3a-499e-a784-8cd1bba940da"),
                            RoleId = new Guid("da138ce8-397b-4c68-98eb-87c211c12883")
                        },
                        new
                        {
                            UserId = new Guid("d724d7e7-b0df-47a7-989c-c373eff365a8"),
                            RoleId = new Guid("2ef4db94-34d6-4264-aebc-eeb0d2908a97")
                        },
                        new
                        {
                            UserId = new Guid("d724d7e7-b0df-47a7-989c-c373eff365a8"),
                            RoleId = new Guid("d089bf57-5915-418c-bbbf-f19e453aee79")
                        },
                        new
                        {
                            UserId = new Guid("76faed9e-cca9-4e5b-98bf-837fa3bdd501"),
                            RoleId = new Guid("2ef4db94-34d6-4264-aebc-eeb0d2908a97")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
