// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250321124725_UpdatedSeed")]
    partial class UpdatedSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb3d7b10-66d9-42aa-b1df-24445af2c490"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("f06cfd35-4691-4e37-932d-4c351515a973"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("58163706-195e-408e-95bd-c6f4168228a9"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("6b383261-6789-4dc8-9523-658018324d36"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83e56a1b-3995-49b5-8553-ba27f7571bcd"),
                            CreatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8464),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8616),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("68c04a83-164e-4ee9-a8e2-d1cc5796ee1f"),
                            CreatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8892),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8892),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("003952a7-6c42-4bd8-8cd2-a849d17a1097"),
                            CreatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8894),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 21, 12, 47, 24, 987, DateTimeKind.Utc).AddTicks(8894),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("83e56a1b-3995-49b5-8553-ba27f7571bcd"),
                            RoleId = new Guid("f06cfd35-4691-4e37-932d-4c351515a973")
                        },
                        new
                        {
                            UserId = new Guid("83e56a1b-3995-49b5-8553-ba27f7571bcd"),
                            RoleId = new Guid("58163706-195e-408e-95bd-c6f4168228a9")
                        },
                        new
                        {
                            UserId = new Guid("83e56a1b-3995-49b5-8553-ba27f7571bcd"),
                            RoleId = new Guid("6b383261-6789-4dc8-9523-658018324d36")
                        },
                        new
                        {
                            UserId = new Guid("68c04a83-164e-4ee9-a8e2-d1cc5796ee1f"),
                            RoleId = new Guid("f06cfd35-4691-4e37-932d-4c351515a973")
                        },
                        new
                        {
                            UserId = new Guid("68c04a83-164e-4ee9-a8e2-d1cc5796ee1f"),
                            RoleId = new Guid("58163706-195e-408e-95bd-c6f4168228a9")
                        },
                        new
                        {
                            UserId = new Guid("003952a7-6c42-4bd8-8cd2-a849d17a1097"),
                            RoleId = new Guid("f06cfd35-4691-4e37-932d-4c351515a973")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
