// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250326064729_AddOneToManyConnectionWithToken")]
    partial class AddOneToManyConnectionWithToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3237da66-7d56-4d72-adcf-05387e6a201c"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("c59ca3a9-7975-41fa-ac23-35ce8ed395ee"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("17c36ce2-6b5a-4de3-bb16-3d3083b70721"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("51d33d94-bf90-4cac-82cb-a3d00e7413f6"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c2052f6-c3d5-425b-bf51-08aff04dc281"),
                            CreatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3054),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3162),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("f787e458-93e0-41ef-9ba5-2f6bf8ee5a6f"),
                            CreatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3465),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3466),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("c8ce159b-36c8-4ca1-988c-69feac103bb1"),
                            CreatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3467),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsConfirmed = false,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 26, 6, 47, 28, 221, DateTimeKind.Utc).AddTicks(3468),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0c2052f6-c3d5-425b-bf51-08aff04dc281"),
                            RoleId = new Guid("c59ca3a9-7975-41fa-ac23-35ce8ed395ee")
                        },
                        new
                        {
                            UserId = new Guid("0c2052f6-c3d5-425b-bf51-08aff04dc281"),
                            RoleId = new Guid("17c36ce2-6b5a-4de3-bb16-3d3083b70721")
                        },
                        new
                        {
                            UserId = new Guid("0c2052f6-c3d5-425b-bf51-08aff04dc281"),
                            RoleId = new Guid("51d33d94-bf90-4cac-82cb-a3d00e7413f6")
                        },
                        new
                        {
                            UserId = new Guid("f787e458-93e0-41ef-9ba5-2f6bf8ee5a6f"),
                            RoleId = new Guid("c59ca3a9-7975-41fa-ac23-35ce8ed395ee")
                        },
                        new
                        {
                            UserId = new Guid("f787e458-93e0-41ef-9ba5-2f6bf8ee5a6f"),
                            RoleId = new Guid("17c36ce2-6b5a-4de3-bb16-3d3083b70721")
                        },
                        new
                        {
                            UserId = new Guid("c8ce159b-36c8-4ca1-988c-69feac103bb1"),
                            RoleId = new Guid("c59ca3a9-7975-41fa-ac23-35ce8ed395ee")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
