// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250328073528_RenamedTokenTable")]
    partial class RenamedTokenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RolesName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d95b8d6-f349-4ddb-9a09-0fc416d38132"),
                            RolesName = 0
                        },
                        new
                        {
                            Id = new Guid("7cd45859-e536-4e85-af8b-95be916f6c6f"),
                            RolesName = 1
                        },
                        new
                        {
                            Id = new Guid("90fb01b5-4a28-4b05-bf15-61b1b176b314"),
                            RolesName = 2
                        },
                        new
                        {
                            Id = new Guid("69eedaee-d2e6-4493-a4ee-8d2d7eb9310d"),
                            RolesName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64d71b71-6617-47f4-83bd-db4d97928ee5"),
                            CreatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(8711),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(8824),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("e947d533-1dfe-465b-bc2c-f1dae8410063"),
                            CreatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(9115),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(9115),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("67b8e8ef-1518-4560-9748-0e9dffb939d8"),
                            CreatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(9126),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsConfirmed = false,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 28, 7, 35, 27, 308, DateTimeKind.Utc).AddTicks(9126),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("64d71b71-6617-47f4-83bd-db4d97928ee5"),
                            RoleId = new Guid("7cd45859-e536-4e85-af8b-95be916f6c6f")
                        },
                        new
                        {
                            UserId = new Guid("64d71b71-6617-47f4-83bd-db4d97928ee5"),
                            RoleId = new Guid("90fb01b5-4a28-4b05-bf15-61b1b176b314")
                        },
                        new
                        {
                            UserId = new Guid("64d71b71-6617-47f4-83bd-db4d97928ee5"),
                            RoleId = new Guid("69eedaee-d2e6-4493-a4ee-8d2d7eb9310d")
                        },
                        new
                        {
                            UserId = new Guid("e947d533-1dfe-465b-bc2c-f1dae8410063"),
                            RoleId = new Guid("7cd45859-e536-4e85-af8b-95be916f6c6f")
                        },
                        new
                        {
                            UserId = new Guid("e947d533-1dfe-465b-bc2c-f1dae8410063"),
                            RoleId = new Guid("90fb01b5-4a28-4b05-bf15-61b1b176b314")
                        },
                        new
                        {
                            UserId = new Guid("67b8e8ef-1518-4560-9748-0e9dffb939d8"),
                            RoleId = new Guid("7cd45859-e536-4e85-af8b-95be916f6c6f")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
