// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250324132017_RemoveAccessTokenFromTokenEnum")]
    partial class RemoveAccessTokenFromTokenEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1adc37e9-f47b-4e06-9a1d-ed5f0cae09a3"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("8559f703-9d61-42ef-973b-434b6bc5cafe"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("5599d238-8112-4100-8705-5e1511b95017"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("41187b60-757a-4699-91e4-ddc2886a15e1"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Token")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0354cf34-a554-4d40-8a52-00343777d7a4"),
                            CreatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(4746),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(4857),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c0771ca1-dcdd-4789-ab82-a13cc997a967"),
                            CreatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(5108),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(5108),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("efd12259-043e-45b6-8595-cc3d8b6fbf5c"),
                            CreatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(5110),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 24, 13, 20, 16, 866, DateTimeKind.Utc).AddTicks(5110),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0354cf34-a554-4d40-8a52-00343777d7a4"),
                            RoleId = new Guid("8559f703-9d61-42ef-973b-434b6bc5cafe")
                        },
                        new
                        {
                            UserId = new Guid("0354cf34-a554-4d40-8a52-00343777d7a4"),
                            RoleId = new Guid("5599d238-8112-4100-8705-5e1511b95017")
                        },
                        new
                        {
                            UserId = new Guid("0354cf34-a554-4d40-8a52-00343777d7a4"),
                            RoleId = new Guid("41187b60-757a-4699-91e4-ddc2886a15e1")
                        },
                        new
                        {
                            UserId = new Guid("c0771ca1-dcdd-4789-ab82-a13cc997a967"),
                            RoleId = new Guid("8559f703-9d61-42ef-973b-434b6bc5cafe")
                        },
                        new
                        {
                            UserId = new Guid("c0771ca1-dcdd-4789-ab82-a13cc997a967"),
                            RoleId = new Guid("5599d238-8112-4100-8705-5e1511b95017")
                        },
                        new
                        {
                            UserId = new Guid("efd12259-043e-45b6-8595-cc3d8b6fbf5c"),
                            RoleId = new Guid("8559f703-9d61-42ef-973b-434b6bc5cafe")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
