// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    [Migration("20250324065152_NewTokenModel")]
    partial class NewTokenModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd90067f-362e-4d85-a869-4242e8f6a70d"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("00b87896-bb05-4bf2-bd15-9558c0173f9a"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("d0a4ffe3-1343-4b5b-895d-4a0121b2190a"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("e1c125ab-67ed-4267-9664-0688bc6e64ff"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Token")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10925bb9-81d6-4a50-927e-8f28a2d4a6f0"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(1781),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(1889),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("279afb52-89e7-48a5-bae5-3c60e40b91fc"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(2154),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(2154),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("fec513fd-cb5b-4352-8434-27fe702825c5"),
                            CreatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(2156),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 24, 6, 51, 52, 8, DateTimeKind.Utc).AddTicks(2156),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("10925bb9-81d6-4a50-927e-8f28a2d4a6f0"),
                            RoleId = new Guid("00b87896-bb05-4bf2-bd15-9558c0173f9a")
                        },
                        new
                        {
                            UserId = new Guid("10925bb9-81d6-4a50-927e-8f28a2d4a6f0"),
                            RoleId = new Guid("d0a4ffe3-1343-4b5b-895d-4a0121b2190a")
                        },
                        new
                        {
                            UserId = new Guid("10925bb9-81d6-4a50-927e-8f28a2d4a6f0"),
                            RoleId = new Guid("e1c125ab-67ed-4267-9664-0688bc6e64ff")
                        },
                        new
                        {
                            UserId = new Guid("279afb52-89e7-48a5-bae5-3c60e40b91fc"),
                            RoleId = new Guid("00b87896-bb05-4bf2-bd15-9558c0173f9a")
                        },
                        new
                        {
                            UserId = new Guid("279afb52-89e7-48a5-bae5-3c60e40b91fc"),
                            RoleId = new Guid("d0a4ffe3-1343-4b5b-895d-4a0121b2190a")
                        },
                        new
                        {
                            UserId = new Guid("fec513fd-cb5b-4352-8434-27fe702825c5"),
                            RoleId = new Guid("00b87896-bb05-4bf2-bd15-9558c0173f9a")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
