// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.DataAccess.Database;

#nullable disable

namespace UserService.DataAccess.Database.Migrations
{
    [DbContext(typeof(UserServiceDbContext))]
    partial class UserServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RoleName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9c04b56-2b3b-4757-b26d-d67b89850011"),
                            RoleName = 0
                        },
                        new
                        {
                            Id = new Guid("60a966ca-ea80-44e7-bd36-1ac541986bb7"),
                            RoleName = 1
                        },
                        new
                        {
                            Id = new Guid("c6044bf6-c950-4ba0-b99e-3d49b371b35a"),
                            RoleName = 2
                        },
                        new
                        {
                            Id = new Guid("4ae70275-7715-4e64-b549-8f5ad76bb6fb"),
                            RoleName = 3
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("863af892-cd9d-414b-b985-a218e0762949"),
                            CreatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(3666),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "User",
                            PasswordHash = "$2a$11$fMotE2uso.Vl/dInRwOYE.CVTYpLLW9bRv/JxwOcFuISgyclU/XKS",
                            UpdatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(3779),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("82cae4d7-21aa-4597-a9e6-0718abc7a049"),
                            CreatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(4066),
                            Email = "user1@example.com",
                            FirstName = "John",
                            IsConfirmed = true,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$Vmq/dCwgmETEykLr31YlZez.vX2akujpnGBJoXsRFSL9n112KwOLK",
                            UpdatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(4066),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("4d4be795-eec7-4185-a02a-0f99e9c6f6db"),
                            CreatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(4068),
                            Email = "user2@example.com",
                            FirstName = "Jane",
                            IsConfirmed = false,
                            IsDeleted = false,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$fP8SA4QPz5bfUeIS5ZH8LOE8VXKYY1JH6JYfIk5iCCqs6PyV6d8La",
                            UpdatedAt = new DateTime(2025, 3, 31, 7, 16, 9, 299, DateTimeKind.Utc).AddTicks(4068),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("863af892-cd9d-414b-b985-a218e0762949"),
                            RoleId = new Guid("60a966ca-ea80-44e7-bd36-1ac541986bb7")
                        },
                        new
                        {
                            UserId = new Guid("863af892-cd9d-414b-b985-a218e0762949"),
                            RoleId = new Guid("c6044bf6-c950-4ba0-b99e-3d49b371b35a")
                        },
                        new
                        {
                            UserId = new Guid("863af892-cd9d-414b-b985-a218e0762949"),
                            RoleId = new Guid("4ae70275-7715-4e64-b549-8f5ad76bb6fb")
                        },
                        new
                        {
                            UserId = new Guid("82cae4d7-21aa-4597-a9e6-0718abc7a049"),
                            RoleId = new Guid("60a966ca-ea80-44e7-bd36-1ac541986bb7")
                        },
                        new
                        {
                            UserId = new Guid("82cae4d7-21aa-4597-a9e6-0718abc7a049"),
                            RoleId = new Guid("c6044bf6-c950-4ba0-b99e-3d49b371b35a")
                        },
                        new
                        {
                            UserId = new Guid("4d4be795-eec7-4185-a02a-0f99e9c6f6db"),
                            RoleId = new Guid("60a966ca-ea80-44e7-bd36-1ac541986bb7")
                        });
                });

            modelBuilder.Entity("UserService.DataAccess.Models.TokenModel", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserRoles", b =>
                {
                    b.HasOne("UserService.DataAccess.Models.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.DataAccess.Models.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("UserService.DataAccess.Models.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
